# Generated by Django 5.0.6 on 2024-06-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlucoseReadings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reading', models.IntegerField()),
                ('type', models.CharField(choices=[('FASTING', 'Fasting'), ('RANDOM', 'Random'), ('PP', 'Pp')])),
            ],
        ),
    ]
