# Generated by Django 5.0.6 on 2024-06-24 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gluco_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glucosereadings',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 6, 24, 18, 25, 39, 290777)),
        ),
    ]
