# Generated by Django 5.0.6 on 2024-06-24 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gluco_main', '0002_alter_glucosereadings_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glucosereadings',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 6, 24, 18, 26, 58, 213971)),
        ),
        migrations.AlterField(
            model_name='glucosereadings',
            name='type',
            field=models.CharField(choices=[('FASTING', 'Fasting'), ('RANDOM', 'Random'), ('PP', 'Pp')], default='Fasting'),
        ),
    ]
