# Generated by Django 4.2 on 2024-07-27 05:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gluco_main', '0003_alter_glucosereadings_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='glucosereadings',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='glucosereadings',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 7, 27, 11, 2, 42, 610272)),
        ),
        migrations.AlterField(
            model_name='glucosereadings',
            name='type',
            field=models.CharField(choices=[('FASTING', 'Fasting'), ('RANDOM', 'Random'), ('PP', 'Pp')], default='FASTING', max_length=50),
        ),
    ]
