# Generated by Django 4.2 on 2024-08-05 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gluco_main', '0004_glucosereadings_notes_alter_glucosereadings_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glucosereadings',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 8, 5, 9, 43, 13, 234081, tzinfo=datetime.timezone.utc)),
        ),
    ]
